name: CI
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macOS-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.100'
      - uses: actions/setup-node@v3
        with:
          node-version: '22.20.0'
      - uses: pnpm/action-setup@v2
      - uses: astral-sh/setup-uv@v7
      - name: Test (Unix)
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macOS-latest'
        run: ./build.sh test
      - name: Test (Windows)
        if: matrix.platform == 'windows-latest'
        run: .\build.bat test
