name: test

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
      - uses: actions/setup-node@v6
        with:
          node-version: '22.20.0'
      - uses: pnpm/action-setup@v6
      - uses: astral-sh/setup-uv@v7
      - name: Test (Unix)
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macOS-latest'
        run: ./build.sh test
      - name: Test (Windows)
        if: matrix.platform == 'windows-latest'
        run: .\build.bat test
